### ISSUE TITLE
Unable to build rpm using make rpm command.

### ISSUE THREAD

**Issue by SomanathThilak** [ClusterLabs/pcs#486] opened 2022-03-22 06:34 UTC
Hi 
I am getting the below error when executing make rpm command to build pcs0.10.13 package on linux 8 server.

checking default settings for rhel fedora... rhel (or alike) default settings will be used
checking pip module: pip >= 10.0.0... no (detected: 9.0.3)
checking pip module: setuptools ... yes (detected: 39.2.0)
checking pip module: setuptools-scm ... yes (detected: 1.15.7)
checking pip module: cryptography ... yes (detected: 3.2.1)
checking pip module: lxml ... yes (detected: 4.2.3)
checking pip module: pycurl ... yes (detected: 7.43.0.2)
checking pip module: pyparsing ... yes (detected: 2.1.10)
checking pip module: dacite ... no
configure: error: Python module dacite not found
error: Bad exit status from /var/tmp/rpm-tmp.VejaJG (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.VejaJG (%build)
make: *** [Makefile:1283: rpm] Error 1

Even though the pip3 command lists the dacite module when running make rpm it is shown as not found.

When configure.sh is run manually there are no errors. 

Please help solve the issue.

**Comment by tomjelinek** [comment] 2022-03-22 07:49
Hi,

Thanks for reaching out. Please, share additional info so that we can better understand and reproduce your issue. Can you list a sequence of commands which leads to the error, and the manual run sequence which works? What's your Linux distribution and version? What's your Python version? Are you using Python virtual environment?

**Comment by SomanathThilak** [comment] 2022-03-22 08:20
> Hi,
> 
> Thanks for reaching out. Please, share additional info so that we can better understand and reproduce your issue. Can you list a sequence of commands which leads to the error, and the manual run sequence which works? What's your Linux distribution and version? What's your Python version? Are you using Python virtual environment?

Below is the sequence of step i did,

1. Extracted the pcs tar file
2.  Installed all the required python and ruby dependcies.
3. Executed autogen.sh
4. execute configure.sh with no options. 
5. then ran "make rpm" This is where i am facing the above issue.

I am using RedHat 8.4 version with python 3.6. Also i am not using python virtual environment.

**Comment by tomjelinek** [comment] 2022-03-22 12:56
I'm unable to reproduce your issue. Once I install `dacite` using `pip`, `configure` finds it just fine.

Try running `./configure --enable-local-build`, this will download Python packages and rubygems automatically when you run `make`.

**Comment by ashore1992** [comment] 2022-11-02 07:14
> I'm unable to reproduce your issue. Once I install `dacite` using `pip`, `configure` finds it just fine.
> 
> Try running `./configure --enable-local-build`, this will download Python packages and rubygems automatically when you run `make`.

same issue,when I ./configure --enable-local-build,checking pip module: dacite ... yes,but raises a new issue.

/root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/platform/twisted.py
Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/dacite/config.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/dacite/config.py", line 7
    type_hooks: Dict[Type, Callable[[Any], Any]] = field(default_factory=dict)
              ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/dacite/core.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/dacite/core.py", line 34
    def from_dict(data_class: Type[T], data: Data, config: Optional[Config] = None) -> T:
                            ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/dacite/dataclasses.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/dacite/dataclasses.py", line 14
    def get_default_value_for_field(field: Field) -> Any:
                                         ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/dacite/exceptions.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/dacite/exceptions.py", line 4
    def _name(type_: Type) -> str:
                   ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/dacite/types.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/dacite/types.py", line 8
    type_hooks: Dict[Type, Callable[[Any], Any]], cast: List[Type], target_type: Type, value: Any
              ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/auth.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/auth.py", line 90
    callback_uri: Optional[str] = None,
                ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/autoreload.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/autoreload.py", line 117
    def start(check_time: int = 500) -> None:
                        ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/concurrent.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/concurrent.py", line 52
    def is_future(x: Any) -> bool:
                   ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/curl_httpclient.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/curl_httpclient.py", line 50
    self, max_clients: int = 10, defaults: Optional[Dict[str, Any]] = None
                     ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/escape.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/escape.py", line 43
    def xhtml_escape(value: Union[str, bytes]) -> str:
                          ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/gen.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/gen.py", line 131
    def _value_from_stopiteration(e: Union[StopIteration, "Return"]) -> Any:
                                   ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/http1connection.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/http1connection.py", line 43
    def __init__(self) -> None:
                       ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/httpclient.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/httpclient.py", line 91
    async_client_class: "Optional[Type[AsyncHTTPClient]]" = None,
                      ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/httpserver.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/httpserver.py", line 156
    def __init__(self, *args: Any, **kwargs: Any) -> None:
                            ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/httputil.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/httputil.py", line 67
    def _normalize_header(name: str) -> str:
                              ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/ioloop.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/ioloop.py", line 61
    def fileno(self) -> int:
                     ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/iostream.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/iostream.py", line 98
    def __init__(self, real_error: Optional[BaseException] = None) -> None:
                                 ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/locale.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/locale.py", line 62
    def get(*locale_codes: str) -> "Locale":
                         ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/locks.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/locks.py", line 41
    def __init__(self) -> None:
                       ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/log.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/log.py", line 55
    def _stderr_supports_color() -> bool:
                                 ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/netutil.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/netutil.py", line 57
    port: int,
        ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/options.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/options.py", line 140
    def __init__(self) -> None:
                       ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/platform/asyncio.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/platform/asyncio.py", line 46
    def fileno(self) -> int:
                     ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/platform/caresresolver.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/platform/caresresolver.py", line 35
    def initialize(self) -> None:
                         ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/platform/twisted.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/platform/twisted.py", line 61
    def initialize(self) -> None:
                         ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/process.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/process.py", line 48
    def cpu_count() -> int:
                    ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/queues.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/queues.py", line 60
    future: Future, timeout: Union[None, float, datetime.timedelta]
          ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/routing.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/routing.py", line 194
    self, request: httputil.HTTPServerRequest, **kwargs: Any
                 ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/simple_httpclient.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/simple_httpclient.py", line 53
    def __init__(self, message: str) -> None:
                              ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/tcpclient.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/tcpclient.py", line 57
    addrinfo: List[Tuple],
            ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/tcpserver.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/tcpserver.py", line 126
    ssl_options: Optional[Union[Dict[str, Any], ssl.SSLContext]] = None,
               ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/template.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/template.py", line 227
    def filter_whitespace(mode: str, text: str) -> str:
                              ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/test/asyncio_test.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/test/asyncio_test.py", line 35
    async def add_callback():
            ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/test/concurrent_test.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/test/concurrent_test.py", line 115
    def test_future(self: typing.Any):
                        ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/test/gen_test.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/test/gen_test.py", line 383
    async def f2():
            ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/test/httpclient_test.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/test/httpclient_test.py", line 142
    def get(self) -> None:
                  ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/test/httpserver_test.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/test/httpserver_test.py", line 54
    async def read_stream_body(stream):
            ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/test/httputil_test.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/test/httputil_test.py", line 28
    def form_data_args() -> Tuple[Dict[str, List[bytes]], Dict[str, List[HTTPFile]]]:
                         ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/test/ioloop_test.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/test/ioloop_test.py", line 363
    async def callback():
            ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/test/iostream_test.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/test/iostream_test.py", line 66
    def test_connection_closed(self: typing.Any):
                                   ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/test/locks_test.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/test/locks_test.py", line 359
    async def f():
            ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/test/netutil_test.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/test/netutil_test.py", line 45
    def test_localhost(self: typing.Any):
                           ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/test/process_test.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/test/process_test.py", line 82
    async def f():
            ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/test/queues_test.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/test/queues_test.py", line 166
    async def f():
            ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/test/simple_httpclient_test.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/test/simple_httpclient_test.py", line 149
    def get_app(self: typing.Any):
                    ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/test/tcpserver_test.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/test/tcpserver_test.py", line 51
    async def handle_stream(self, stream, address):
            ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/test/testing_test.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/test/testing_test.py", line 78
    async def callback():
            ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/test/util_test.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/test/util_test.py", line 227
    print("hello", file=f)
                       ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/test/web_test.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/test/web_test.py", line 2376
    def test_flow_control_fixed_body(self: typing.Any):
                                         ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/test/websocket_test.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/test/websocket_test.py", line 202
    async def open(self):
            ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/testing.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/testing.py", line 50
    reuse_port: bool = False, address: str = "127.0.0.1"
              ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/util.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/util.py", line 54
    def _get_emulated_is_finalizing() -> Callable[[], bool]:
                                      ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/web.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/web.py", line 211
    application: "Application",
               ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/websocket.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/websocket.py", line 63
    def compress(self, data: bytes) -> bytes:
                           ^
SyntaxError: invalid syntax

Compiling /root/rpmbuild/BUILDROOT/pcs-0.10-1.14.dirty.a.ky10.loongarch64/usr/lib64/pcs/pcs_bundled/packages/tornado/wsgi.py ...
  File "/usr/lib64/pcs/pcs_bundled/packages/tornado/wsgi.py", line 51
    def to_wsgi_str(s: bytes) -> str:
                     ^
SyntaxError: invalid syntax

错误：/var/tmp/rpm-tmp.rZWF43 (%install) 退出状态不好


RPM 构建错误：
    /var/tmp/rpm-tmp.rZWF43 (%install) 退出状态不好
make: *** [Makefile:1303：rpm] 错误 1

**Comment by tomjelinek** [comment] 2022-11-02 13:39
Hi @ashore1992,

These seem to be errors coming from Python. What Python version are you using?  Pcs requires Python 3.6 or newer.

**Comment by ashore1992** [comment] 2022-11-03 01:07
> Hi @ashore1992,
> 
> These seem to be errors coming from Python. What Python version are you using? Pcs requires Python 3.6 or newer.

[root@test pcs]# python3 --version
Python 3.7.4

**Comment by tomjelinek** [comment] 2022-11-03 16:44
@ashore1992,

I'm unable to reproduce your issue. Can you post how exactly you run `autogen.sh`, `configure` and `make` and their outputs? Do you have more than one Python version installed on your machine?

**Comment by ashore1992** [comment] 2022-11-04 01:39
my system has all python 
[root@test pcs]# python
python                                        python3.7m
python2                                       python3.7m-config
python2.7                                     python3.7m-loongarch64-config
python2.7-config                              python3-chardetect
python2.7-debug                               python3-config
python2.7-debug-config                        python3-coverage
python2-config                                python3-pyinotify
python2-debug                                 python-argcomplete-check-easy-install-script
python2-debug-config                          python-argcomplete-tcsh
python3                                       python-config
python3.7                                     python-debug
python3.7-config                              python-debug-config
now I copy all my outputs,please help me analyse,it's too long，so Divide into multiple parts

[root@test pcs]# ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf
autoreconf: configure.ac: not using Autoheader
autoreconf: running: automake --add-missing --copy --no-force
autoreconf: Leaving directory `.'
Now run ./configure and make

[root@test pcs]# ./configure --enable-local-build
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking build system type... loongarch64-unknown-linux-gnu
checking host system type... loongarch64-unknown-linux-gnu
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for gawk... (cached) gawk
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for a Python interpreter with version >= 3.6... python3
checking for python3... /usr/bin/python3
checking for python3 version... 3.7
checking for python3 platform... linux
checking for python3 script directory... ${prefix}/lib/python3.7/site-packages
checking for python3 extension module directory... ${exec_prefix}/lib64/python3.7/site-packages
checking for systemd... yes
checking for pkg-conf systemd var systemdsystemunitdir... yes (detected: /usr/lib/systemd/system)
checking for pkg-conf systemd var systemdsystemunitpath... yes (detected: /etc/systemd/system:/etc/systemd/system:/run/systemd/system:/usr/local/lib/systemd/system:/usr/lib/systemd/system:/usr/lib/systemd/system:/lib/systemd/system)
checking for ruby... /usr/bin/ruby
checking for ruby... yes
checking for pkg-conf ruby var ruby_version... yes (detected: 2.5.0)
checking for gem... gem
checking for time... time
checking for tar... tar
checking for wget... wget
checking for fc-match... fc-match
checking linux distribution... kylin
checking default settings for kylin ... kylin (or alike) default settings will be used
checking pip module: pip >= 10.0.0... yes (detected: 18.0)
checking pip module: setuptools ... yes (detected: 40.4.3)
checking pip module: setuptools-scm ... yes (detected: 3.1.0)
checking pip module: wheel ... yes (detected: 0.31.1)
checking pip module: cryptography ... yes (detected: 2.6.1)
checking pip module: lxml ... yes (detected: 4.2.3)
checking pip module: pycurl ... yes (detected: 7.43.0.2)
checking pip module: pyparsing ... yes (detected: 2.2.0)
checking pip module: dacite ... yes (detected: 1.6.0)
checking pip module: tornado >= 6.0.0... yes (detected: 6.2)
checking pip module: python-dateutil >= 2.7.0... yes (detected: 2.7.0)
checking pip module: pyagentx ... yes (detected: 0.4.1)
checking ruby gem: power_assert... yes (detected: 1.1.1)
checking ruby gem: test-unit... yes (detected: 3.2.7)
checking ruby gem: backports... yes (detected: 3.23.0)
checking ruby gem: daemons... yes (detected: 1.4.1)
checking ruby gem: ethon... yes (detected: 0.15.0)
checking ruby gem: ffi... yes (detected: 1.15.5)
checking ruby gem: eventmachine... yes (detected: 1.2.7)
checking ruby gem: json... yes (detected: 2.6.2)
checking ruby gem: mustermann... yes (detected: 2.0.2)
checking ruby gem: open4... yes (detected: 1.3.4)
checking ruby gem: rack... yes (detected: 2.2.4)
checking ruby gem: rack-protection... yes (detected: 2.2.2)
checking ruby gem: rack-test... yes (detected: 2.0.2)
checking ruby gem: sinatra... yes (detected: 2.2.2)
checking ruby gem: tilt... yes (detected: 2.0.11)
checking ruby gem: thin... yes (detected: 1.8.1)
checking ruby gem: rexml... yes (detected: 3.2.5)
checking ruby gem: webrick... yes (detected: 1.4.2)
checking for bash... /bin/sh
checking for systemctl... /usr/bin/systemctl
checking for killall... /usr/bin/killall
checking for rm... /usr/bin/rm
checking for find... /usr/bin/find
checking for pkg-conf pacemaker var daemon_user... not found, using default hacluster
checking for pkg-conf pacemaker var daemon_group... not found, using default haclient
checking for pkg-conf pacemaker var daemondir... not found, using default /usr/libexec/pacemaker
checking for pkg-conf pacemaker var exec_prefix... not found, using default /usr
checking for pkg-conf pacemaker var prefix... not found, using default /usr
checking for pkg-conf pacemaker var configdir... not found, using default /var/lib/pacemaker/cib
checking for pkg-conf pacemaker var schemadir... not found, using default /usr/share/pacemaker
checking for pkg-conf corosync var exec_prefix... yes (detected: /usr)
checking for pkg-conf corosync var prefix... yes (detected: /usr)
checking for pkg-conf corosync var logdir... not found, using default /var/log/cluster
checking for pkg-conf corosync-qdevice var exec_prefix... not found, using default /usr
checking for pkg-conf corosync-qdevice var confdir... not found, using default /etc/corosync
checking for pkg-conf sbd var confdir... not found, using default /etc/sysconfig
checking for pkg-conf sbd var exec_prefix... not found, using default /usr
checking for pkg-conf fence-agents var exec_prefix... not found, using default /usr
checking for pkg-conf resource-agents var ra_api_dtd... not found, using default /usr/share/resource-agents/ra-api-1.dtd
checking for pkg-conf resource-agents var ra_tmp_dir... not found, using default /run/resource-agents
checking for pkg-conf booth var confdir... not found, using default /etc/booth
checking for pkg-conf booth var exec_prefix... not found, using default /usr
checking for GNU date... yes
checking for BSD date... no
checking for date type... gnu
checking whether GNU date supports --date... yes
checking whether GNU date supports --utc... yes
configure: trying to determine source epoch
checking for source epoch in $SOURCE_EPOCH... no
checking for source epoch in source_epoch file... no
checking for source epoch baked in by gitattributes export-subst... no
checking for source epoch in $SOURCE_DATE_EPOCH... no
checking whether git log can provide a source epoch... yes
configure: using source epoch 2022-11-03
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating setup.py
config.status: creating setup.cfg
config.status: creating data/Makefile
config.status: creating pcs/Makefile
config.status: creating pcs/settings.py
config.status: creating pcs/snmp/pcs_snmp_agent.service
config.status: creating pcs/snmp/settings.py
config.status: creating pcs/snmp/pcs_snmp_agent.8
config.status: creating pcs/pcs.8
config.status: creating pcs_test/Makefile
config.status: creating pcs_test/settings.py
config.status: creating pcsd/Makefile
config.status: creating pcsd/pcsd.8
config.status: creating pcsd/pcsd-cli.rb
config.status: creating pcsd/pcsd-ruby.service
config.status: creating pcsd/pcsd.service
config.status: creating pcsd/settings.rb
config.status: creating pcsd/logrotate/pcsd
config.status: creating pcs/pcs
config.status: creating pcs/pcs_internal
config.status: creating pcs/snmp/pcs_snmp_agent
config.status: creating pcs_test/smoke.sh
config.status: creating pcs_test/pcs_for_tests
config.status: creating pcs_test/suite
config.status: creating pcs_test/tools/bin_mock/pcmk/crm_resource
config.status: creating pcs_test/tools/bin_mock/pcmk/pacemaker-fenced
config.status: creating pcsd/pcsd
config.status: creating scripts/pcsd.sh

**Comment by tomjelinek** [comment] 2023-03-03 11:52
> also, there's a prompt, I don't know if this has any effect:
/usr/lib/python3.7/site-packages/setuptools/dist.py:407: UserWarning: The version specified ('0.10.14.4-f986') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details. "details." % self.metadata.version

This comes from a new version of setuptools. I didn't have such new version installed, so I couldn't reproduce it. However, it is now fixed by https://github.com/ClusterLabs/pcs/commit/0b6c1e7f6a8636126a8a7fcdef478ef396ceb68b

**Comment by tomjelinek** [comment] 2024-01-08 12:09
I'm closing this issue for inactivity. Feel free to reopen it if you have further questions.

**Closed by tomjelinek** 2024-01-08 12:09 UTC
