### ISSUE TITLE
Cannot create resource

### ISSUE THREAD

**Issue by eileon** [ClusterLabs/pcs#113] opened 2016-10-17 15:24 UTC
Doing :

`pcs resource create ClusterIP ocf:heartbeat:IPaddr2 ip=192.168.1.100 cidr_netmask=32 op monitor interval=30s nic=enp2s0 --force`

i got :

```
[root@archie mou]# pcs resource create ClusterIP ocf:heartbeat:IPaddr2 ip=192.168.1.100 cidr_netmask=32 op monitor interval=30s nic=enp2s0 --force
Error: Unable to update cib
Call cib_replace failed (-203): Update does not conform to the configured schema
<cib crm_feature_set="3.0.11" validate-with="pacemaker-2.6" epoch="15" num_updates="0" admin_epoch="0" cib-last-written="Mon Oct 17 17:14:47 2016" update-origin="archie" update-client="cibadmin" update-user="root" have-quorum="1" dc-uuid="1">
  <configuration>
    <crm_config>
      <cluster_property_set id="cib-bootstrap-options">
        <nvpair id="cib-bootstrap-options-have-watchdog" name="have-watchdog" value="false"/>
        <nvpair id="cib-bootstrap-options-dc-version" name="dc-version" value="1.1.15-92ce5ab"/>
        <nvpair id="cib-bootstrap-options-cluster-infrastructure" name="cluster-infrastructure" value="corosync"/>
        <nvpair id="cib-bootstrap-options-cluster-name" name="cluster-name" value="archiclust"/>
        <nvpair id="cib-bootstrap-options-stonith-enabled" name="stonith-enabled" value="false"/>
        <nvpair id="cib-bootstrap-options-no-quorum-policy" name="no-quorum-policy" value="ignore"/>
      </cluster_property_set>
    </crm_config>
    <nodes>
      <node id="1" uname="archie"/>
      <node id="2" uname="archicomble"/>
    </nodes>
    <resources>
      <primitive class="ocf" id="ClusterIP" provider="heartbeat" type="IPaddr2">
        <instance_attributes id="ClusterIP-instance_attributes">
          <nvpair id="ClusterIP-instance_attributes-ip" name="ip" value="192.168.1.100"/>
          <nvpair id="ClusterIP-instance_attributes-cidr_netmask" name="cidr_netmask" value="32"/>
        </instance_attributes>
        <operations>
          <op id="ClusterIP-monitor-interval-30s" interval="30s" name="monitor" nic="enp2s0"/>
        </operations>
      </primitive>
    </resources>
    <constraints/>
  </configuration>
  <status>
    <node_state id="1" uname="archie" in_ccm="true" crmd="online" crm-debug-origin="do_state_transition" join="member" expected="member">
      <transient_attributes id="1">
        <instance_attributes id="status-1">
          <nvpair id="status-1-shutdown" name="shutdown" value="0"/>
        </instance_attributes>
      </transient_attributes>
      <lrm id="1">
        <lrm_resources/>
      </lrm>
    </node_state>
    <node_state id="2" in_ccm="true" crmd="online" crm-debug-origin="do_state_transition" uname="archicomble" join="member" expected="member">
      <lrm id="2">
        <lrm_resources/>
      </lrm>
      <transient_attributes id="2">
        <instance_attributes id="status-2">
          <nvpair id="status-2-shutdown" name="shutdown" value="0"/>
        </instance_attributes>
      </transient_attributes>
    </node_state>
  </status>
</cib>
```
Problem is :

```
Error: Unable to update cib
Call cib_replace failed (-203): Update does not conform to the configured schema
```
```
[root@archie cib]# cibadmin --upgrade --force
Call cib_upgrade failed (-211): Schema is already the latest available

[root@archie cib]# pcs cluster cib cib-upgrade
```
No way. Every same

**Comment by idevat** [comment] 2016-10-18 05:56
Hi eileon,

this is the known bug (see https://bugzilla.redhat.com/show_bug.cgi?id=1382597). The problem is that  "nic" is currently not a valid option. We plan fix this bug as proposed in the mentioned bugzilla.

**Comment by eileon** [comment] 2016-10-18 06:37
Today i did create resource successfully without nic option. And i get :

```
[root@archie cluster]# pcs status
Cluster name: archiclust
WARNING: corosync and pacemaker node names do not match (IPs used in setup?)
Stack: corosync
Current DC: archie (version 1.1.15-92ce5ab) - partition with quorum
Last updated: Tue Oct 18 08:25:31 2016
Last change: Tue Oct 18 08:22:12 2016 by root via cibadmin on archie

2 nodes configured
1 resource configured

Online: [ archicomble archie ]

Full list of resources:

 ClusterIP	(ocf::heartbeat:IPaddr2):	FAILED (blocked)[ archie archicomble ]

Failed Actions:
* ClusterIP_stop_0 on archie 'unknown error' (1): call=6, status=complete, exitreason='none',
    last-rc-change='Tue Oct 18 08:22:13 2016', queued=0ms, exec=6ms
* ClusterIP_stop_0 on archicomble 'unknown error' (1): call=6, status=complete, exitreason='none',
    last-rc-change='Tue Oct 18 08:18:46 2016', queued=0ms, exec=5ms


Daemon Status:
  corosync: active/disabled
  pacemaker: active/enabled
  pcsd: active/enabled
```
Do you know the meaning of this unkown error ?

**Comment by idevat** [comment] 2016-10-18 06:56
To clarify: "nic" is a resource option - not "op" option. So probably you wanted `pcs resource create ClusterIP ocf:heartbeat:IPaddr2 ip=192.168.1.100 cidr_netmask=32  nic=enp2s0 op monitor interval=30s` ("nic" before "op").

**Comment by eileon** [comment] 2016-10-18 07:09
That is right :
`
[root@archie pcs]# pcs resource create ClusterIP ocf:heartbeat:IPaddr2 ip=192.168.1.100 cidr_netmask=32  nic=enp2s0 op monitor interval=30s --force
`
is working fine. But i get the same Failed Actions as above with :

```
ClusterIP_stop_0 on archie 'unknown error'
ClusterIP_stop_0 on archie 'unknown error'
```

**Comment by tomjelinek** [comment] 2016-10-19 07:41
This is out of pcs scope. Check pacemaker / corosync logs to see what went wrong. Also `pcs resource debug-*` commands may help you debugging the issue. If you cannot figure it out by yourself, I recommend you to check out or ask at Cluster Labs mailing list http://clusterlabs.org/mailman/listinfo/users

Putting `--force` flag to pcs commands automatically is not really a best practice. It may make the command to end successfully but the underlying issue may just manifests itself later. For example in this case pcs would have told you the 'nic' option is not a valid op option and based on that you could figure out the command was not correct and what needs to be done.

Closing this as the pcs issue has been resolved.

**Closed by tomjelinek** 2016-10-19 07:41 UTC
