### ISSUE TITLE
Can not run pcs status

### ISSUE THREAD

**Issue by parhamdoustdar** [ClusterLabs/pcs#100] opened 2016-07-10 11:18 UTC
When I try to run `pcs status`, i get this error:

```
[root@elf-app-03 ~]# pcs status
Cluster name:
Traceback (most recent call last):
  File "/sbin/pcs", line 219, in <module>
    main(sys.argv[1:])
  File "/sbin/pcs", line 159, in main
    cmd_map[command](argv)
  File "/usr/lib/python2.7/site-packages/pcs/status.py", line 16, in status_cmd
    full_status()
  File "/usr/lib/python2.7/site-packages/pcs/status.py", line 56, in full_status

    if utils.corosyncPacemakerNodeCheck():
  File "/usr/lib/python2.7/site-packages/pcs/utils.py", line 1717, in corosyncPa
cemakerNodeCheck
    cs_nodes = getCorosyncNodesID()
  File "/usr/lib/python2.7/site-packages/pcs/utils.py", line 1685, in getCorosyn
cNodesID
    cs_nodes[node_list_node_mapping[m.group(1)]] = m.group(2)
KeyError: '0'
```

Here is the output of `corosync-cmapctl`:

```
[root@elf-app-03 ~]# corosync-cmapctl -b nodelist.node
nodelist.node.0.ring0_addr (str) = 192.168.100.54
nodelist.node.1.ring0_addr (str) = 192.168.100.53
nodelist.node.2.ring0_addr (str) = 192.168.100.52
```

As far as I can tell, the problem is with this line in `utils.py` that says:

```
        m = re.match("nodelist.node.(\d+).nodeid.*= (.*)",line)
```

As I showed, the output of my command doesn't have such a thing.

Here is more information on what I'm using:

* CentOS 7
* Corosync 2.3.4
* Pacemaker 1.1.13
* PCS 0.9.143

Here is the output of `pcs status` after I manually change `utils.py` and remove the `nodeid` from the line I mentioned earlier:

```
[root@elf-app-03 ~]# pcs status
Cluster name:
Last updated: Sun Jul 10 15:47:32 2016          Last change: Sun Jul 10 11:16:40
 2016 by root via crm_resource on elf-app-01
Stack: corosync
Current DC: elf-app-02 (version 1.1.13-a14efad) - partition with quorum
3 nodes and 6 resources configured
```

Please note that for some reason, my cluster doesn't seem to have a name -- maybe that causes the problem?

Thanks in advance.

**Comment by tomjelinek** [comment] 2016-07-11 14:17
Thank you for very detailed report. It helped me to find and fix the issue quickly.

The problem is caused most probably by not specifying node ids in `corosync.conf`. This is what `corosync-cmapctl` output looks like with node ids specified:
```
# corosync-cmapctl -b nodelist.node
nodelist.node.0.nodeid (u32) = 1
nodelist.node.0.ring0_addr (str) = rh72-node1
nodelist.node.1.nodeid (u32) = 2
nodelist.node.1.ring0_addr (str) = rh72-node2
```

Fixed in https://github.com/ClusterLabs/pcs/commit/4ce01f0dab20fd02e700e3803d2a5aecebb7bb43

Even though this issue was not caused by missing cluster name, I strongly recommend to set it up as it may cause other issues.

**Closed** 2016-07-25 16:30 UTC
